# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTextInput():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_textInput(self):
        self.driver.get("http://uitestingplayground.com/")
        self.driver.set_window_size(1102, 984)
        self.driver.find_element(By.LINK_TEXT, "Text Input").click()
        self.driver.find_element(By.ID, "newButtonName").click()
        self.driver.find_element(By.ID, "newButtonName").send_keys("New button")
        self.driver.find_element(By.ID, "updatingButton").click()
        self.driver.close()
