# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestHiddenLayers():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_hiddenLayers(self):
        self.driver.get("http://uitestingplayground.com/")
        self.driver.set_window_size(1102, 984)
        # Click on the hidden layers link
        self.driver.find_element(By.LINK_TEXT, "Hidden Layers").click()
        # Click on the green button
        self.driver.find_element(By.ID, "greenButton").click()
        # Click on the blue button
        self.driver.find_element(By.ID, "blueButton").click()
