# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestClassAtribute():

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_classAtribute(self):
        # Test name: Class Atribute
        # Homepage
        self.driver.get("http://uitestingplayground.com/")

        self.driver.set_window_size(1102, 984)

        # Click on the Class Attribute link
        self.driver.find_element(By.LINK_TEXT, "Class Attribute").click()

        # Click on the blue button
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()

        # Click on the button in the pop up notification
        assert self.driver.switch_to.alert.text == "Primary button pressed"

